function Show-Help {
    Write-Host ""
    Write-Host "Cursor Autolook — Cursor as execution hub" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "简易模式:  .\cursor-autolook.ps1 menu   （默认无参数即打开菜单）"
    Write-Host ""
    Write-Host "Commands:"
    Write-Host "  init"
    Write-Host "  new-project -Name NAME"
    Write-Host "  new-task -Project PROJECT -Title TITLE [-TaskType bugfix|refactor|review|general] [-Assignee ...] [-Reviewer ...] [-Artifacts a,b] [-TestCommand ...] [-MaxAttempts N]"
    Write-Host "           [-AutoAdvanceOnGatePass]                # allow automation-hub to push in_progress -> in_review when acceptance gate passes"
    Write-Host "           [-WorkerModel ...] [-CcSwitchModel ...]  # reported model and cc-switch model"
    Write-Host "           [-OllamaModel qwen3.5:9b]                # local model when assignee=Ollama; or runtime/autolook.config.json defaultOllamaModel when omitted"
    Write-Host "           [-NoAutoRoute]                            # disable model routing for this task"
    Write-Host "           [-ApproveExpensive]                       # required when policy demands explicit approval"
    Write-Host "  set-task -Project PROJECT -TaskId TASK [-Status ready|in_progress|in_review|done|blocked] [-Note ...]"
    Write-Host "  agent-done -Project PROJECT -TaskId TASK [-Note ...] [-AutoContinue]"
    Write-Host "             [-WorkerModel ...] [-CcSwitchModel ...] [-Source ...] [-TraceId ...] [-SessionId ...]"
    Write-Host "             # Omit -CcSwitchModel: match Claude model line in cc-switch.log near TraceId/SessionId"
    Write-Host "  close-open [-Project PROJECT]                 # one-click close non-blocked open tasks"
    Write-Host "  consume-callbacks                                  # consume runtime/callbacks/*.json queue"
    Write-Host "  follow-feed [-Project P] [-FeedTail N] [-FeedOnce] [-FeedNewWindow]  # -FeedNewWindow pops a new PowerShell window"
    Write-Host "  watch-callbacks [-Interval 30] [-MaxRounds 0]     # continuously consume callback queue"
    Write-Host "  status"
    Write-Host "  next -Project PROJECT"
    Write-Host "  reconcile -Project PROJECT"
    Write-Host "  watchdog -Project PROJECT [-Interval 30] [-MaxRounds 0] [-LeaseMinutes 45]"
    Write-Host "           [-OpenCodeMaxParallel 2] [-OpenCodeBackoffSeconds 120]"
    Write-Host "           [-MaxConcurrentTasks 1] [-LocalModelMaxParallel 1]  # raise MaxConcurrentTasks to overlap cloud workers; keep LocalModelMaxParallel=1 so Ollama stays serialized"
    Write-Host "  automation-hub -Project PROJECT [-Interval 10] [-HubMaxCycles 0] [-SkipHubConsumeCallbacks] [-HubAutoAdvanceGate]"
    Write-Host "                 # loop: consume-callbacks -> optional gate auto-advance -> single watchdog round (raise MaxConcurrentTasks for parallel cloud workers)"
    Write-Host "  worker-queue -Project PROJECT [-WorkerQueuePrepBrief]  # export runtime/worker-queue/PROJECT.json for sidecar agents"
    Write-Host "  serve-worker-queue -Project PROJECT [-WorkerQueueServePort N]  # 127.0.0.1 visual board + /api/worker-queue.json"
    Write-Host "  review -Project PROJECT -TaskId TASK"
    Write-Host "  prep-brief -Project PROJECT -TaskId TASK     # build cache-friendly prompt brief"
    Write-Host "  cache-stats                                        # prompt cache hit/miss stats"
    Write-Host "  set-project-prefix -Project PROJECT -ProjectPrefix TEXT"
    Write-Host "  enter-workflow -Project PROJECT [-TaskId TASK]   # bootstrap status/metrics/brief"
    Write-Host "  current-workflow                                   # show active workflow marker"
    Write-Host "  routing config: runtime/routing.json               # task routing + expensive provider policy"
    Write-Host "                                                     # apinebula: default disabled; require approval; only when others all blocked"
    Write-Host "  dashboard -Project PROJECT [-ClaudeCount N] [-DashboardSinglePane]   # default: split WT + Codex tab; -DashboardSinglePane: one pane (Ctrl+C then type in same pane)"
    Write-Host "  evolve-supervisor                                  # bounded cache-key evolution from runtime evidence"
    Write-Host "  evolve-routing                                     # bounded assignee/modelTier evolution from task outcomes"
    Write-Host "  evolve-reliability                                 # bounded reviewer evolution + agent reliability snapshot"
    Write-Host "  ops-report [-Project PROJECT]                # production ops report (success/blocked/retry/fallback)"
    Write-Host "  supervisor-evolution                               # show evolution config and recent steps"
    Write-Host "  serve-codex [-CodexServePort N]                     # Codex app-server on ws://127.0.0.1:<defaults.codex> (16128); optional AUTOLOOK_CODEX_WS_TOKEN_FILE"
    Write-Host "  serve-deepseek                                      # start deepseek runtime api on isolated port"
    Write-Host "  serve-opencode [-AllowInsecure]                     # start opencode headless server on isolated port"
    Write-Host "  metrics [-Project PROJECT]"
    Write-Host "  check-ports"
    Write-Host "  quick-check"
    Write-Host "  e2e-check"
    Write-Host "  stress-scheduler [-StressTasks N] [-StressLocalHeavyTasks M] [-StressIterations K] [-StressKeepProject]"
    Write-Host "                                   # synthetic load: raises MaxConcurrentTasks to 4 while fixing LocalModelMaxParallel=1 so Ollama never fans out"
    Write-Host "  kxnx-audit                       # one-click real audit workflow template for D:\GIT\kxnx-style reverse-engineering repo"
    Write-Host "  doctor                         # ports + syntax + callbacks queue + CC Switch paths + config hints"
    Write-Host "  list-callbacks                 # show pending runtime/callbacks/*.json (no consume)"
    Write-Host "  ccswitch-providers             # DB vs cc-switch-router.config.json (needs python)"
    Write-Host "                                 # optional: runtime/autolook.config.json { defaultOllamaModel } for new-task"
    Write-Host ""
}
